version: '3'
services:
  db:

    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  memurai:
    image: 'memurai/memurai-s3-develop:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
volumes:
  mysql-data: